version: '3.8'

services:
  bot:
    deploy:
      resources:
        limits:
          memory: "128M"
    restart: unless-stopped
    image: 'ghcr.io/kagchi/sotn-discord-bot:latest-dev'
    env_file:
      - .env
    networks:
      internet:
        aliases:
          - bot.internet

networks:
  sotn-internet:
    ipam:
      driver: default
      config:
        - subnet: 10.0.32.0/24
    internal: false